### ISSUE TITLE
CORS Problem

### ISSUE THREAD

**Issue by ramiborni** [ItzSylex/JojoAPI#1]
I was trying to build a small web app with your API
and i'm getting this unfortunately in the console log
 
`
Access to fetch at 'https://jojoapi.herokuapp.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

Could you fix that please?

**Comment by ItzSylex** [comment]
Hey

This project has been in hiatus for a while, I'll make sure to take a look
a that and will follow up with you as soon as I can

Thanks for letting me know

**Comment by ItzSylex** [comment]
I followed the documentation on [Flask-Cors](https://flask-cors.readthedocs.io/en/latest/) hoping these changes will fix your issue. 

I have never worked with Cross-origin requests before, so please test it and let me know how it goes.

**Comment by ramiborni** [comment]
Worked , Thank you for fast reply <3 Good luck in your future projects
