### ISSUE TITLE
Is this repo accepting contributions for Stone Ocean?

### ISSUE THREAD

**Issue by MaitrayBhardwaj** [ItzSylex/JojoAPI#2]
Sorry for creating an issue, had to contact this way. If it is accepting, then I just need to add the data in /app/data.json right?

**Comment by ItzSylex** [comment]
Hey, 

I was re writing the scraper to get the data for all seasons, but kinda stopped working on it. I am currently not taking contributions, but I can continue working on it to finish it.

**Comment by MaitrayBhardwaj** [comment]
I see, thank you for your response.

**Comment by ItzSylex** [comment]
Hey @MaitrayBhardwaj I have pushed and deployed a new version now including Stone Ocean data, I have also made some changes on how the data was structured so make sure to keep that in mind. Please let me know if u find any issues

**Comment by MaitrayBhardwaj** [comment]
Hey @ItzSylex

Thank you for the update! Sure, I will keep that in mind.
